/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as Onshape_connectorRouteImport } from './routes/onshape_connector'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainEquipmentRouteImport } from './routes/_main.equipment'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthStatusRouteImport } from './routes/auth/status'
import { Route as MainKanbanIndexRouteImport } from './routes/_main.kanban.index'
import { Route as MainKanbanDoneRouteImport } from './routes/_main.kanban.done'
import { Route as ApiEquipmentIndexRouteImport } from './routes/api/equipment.index'
import { Route as ApiEquipmentIdRouteImport } from './routes/api/equipment.$id'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files.$'
import { Route as ApiKanbanEventsRouteImport } from './routes/api/kanban/events'
import { Route as ApiOnshapePartsRouteImport } from './routes/api/onshape/parts'
import { Route as ApiOnshapeThumbnailRouteImport } from './routes/api/onshape/thumbnail'
import { Route as ApiOnshapeTokenRouteImport } from './routes/api/onshape/token'
import { Route as ApiOnshapeVersionRouteImport } from './routes/api/onshape/version'
import { Route as ApiProcessesIndexRouteImport } from './routes/api/processes.index'
import { Route as ApiProcessesIdRouteImport } from './routes/api/processes.$id'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users.index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as AuthOnshapeIndexRouteImport } from './routes/auth/onshape.index'
import { Route as AuthOnshapeCallbackRouteImport } from './routes/auth/onshape.callback'
import { Route as ApiEquipmentIdImageRouteImport } from './routes/api/equipment.$id.image'
import { Route as ApiKanbanCardsIndexRouteImport } from './routes/api/kanban/cards.index'
import { Route as ApiKanbanCardsIdRouteImport } from './routes/api/kanban/cards.$id'
import { Route as ApiKanbanConfigIndexRouteImport } from './routes/api/kanban/config.index'
import { Route as ApiKanbanConfigColumnsRouteImport } from './routes/api/kanban/config.columns'
import { Route as ApiMfgPartsActionsRouteImport } from './routes/api/mfg/parts.actions'
import { Route as ApiKanbanCardsIdAssignRouteImport } from './routes/api/kanban/cards.$id.assign'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const Onshape_connectorRoute = Onshape_connectorRouteImport.update({
  id: '/onshape_connector',
  path: '/onshape_connector',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainEquipmentRoute = MainEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => MainRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStatusRoute = AuthStatusRouteImport.update({
  id: '/auth/status',
  path: '/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const MainKanbanIndexRoute = MainKanbanIndexRouteImport.update({
  id: '/kanban/',
  path: '/kanban/',
  getParentRoute: () => MainRoute,
} as any)
const MainKanbanDoneRoute = MainKanbanDoneRouteImport.update({
  id: '/kanban/done',
  path: '/kanban/done',
  getParentRoute: () => MainRoute,
} as any)
const ApiEquipmentIndexRoute = ApiEquipmentIndexRouteImport.update({
  id: '/api/equipment/',
  path: '/api/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEquipmentIdRoute = ApiEquipmentIdRouteImport.update({
  id: '/api/equipment/$id',
  path: '/api/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanEventsRoute = ApiKanbanEventsRouteImport.update({
  id: '/api/kanban/events',
  path: '/api/kanban/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnshapePartsRoute = ApiOnshapePartsRouteImport.update({
  id: '/api/onshape/parts',
  path: '/api/onshape/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnshapeThumbnailRoute = ApiOnshapeThumbnailRouteImport.update({
  id: '/api/onshape/thumbnail',
  path: '/api/onshape/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnshapeTokenRoute = ApiOnshapeTokenRouteImport.update({
  id: '/api/onshape/token',
  path: '/api/onshape/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnshapeVersionRoute = ApiOnshapeVersionRouteImport.update({
  id: '/api/onshape/version',
  path: '/api/onshape/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessesIndexRoute = ApiProcessesIndexRouteImport.update({
  id: '/api/processes/',
  path: '/api/processes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessesIdRoute = ApiProcessesIdRouteImport.update({
  id: '/api/processes/$id',
  path: '/api/processes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnshapeIndexRoute = AuthOnshapeIndexRouteImport.update({
  id: '/auth/onshape/',
  path: '/auth/onshape/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnshapeCallbackRoute = AuthOnshapeCallbackRouteImport.update({
  id: '/auth/onshape/callback',
  path: '/auth/onshape/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEquipmentIdImageRoute = ApiEquipmentIdImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiEquipmentIdRoute,
} as any)
const ApiKanbanCardsIndexRoute = ApiKanbanCardsIndexRouteImport.update({
  id: '/api/kanban/cards/',
  path: '/api/kanban/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanCardsIdRoute = ApiKanbanCardsIdRouteImport.update({
  id: '/api/kanban/cards/$id',
  path: '/api/kanban/cards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanConfigIndexRoute = ApiKanbanConfigIndexRouteImport.update({
  id: '/api/kanban/config/',
  path: '/api/kanban/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanConfigColumnsRoute = ApiKanbanConfigColumnsRouteImport.update({
  id: '/api/kanban/config/columns',
  path: '/api/kanban/config/columns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMfgPartsActionsRoute = ApiMfgPartsActionsRouteImport.update({
  id: '/api/mfg/parts/actions',
  path: '/api/mfg/parts/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanCardsIdAssignRoute = ApiKanbanCardsIdAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => ApiKanbanCardsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/onshape_connector': typeof Onshape_connectorRoute
  '/signin': typeof SigninRoute
  '/equipment': typeof MainEquipmentRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/status': typeof AuthStatusRoute
  '/kanban/done': typeof MainKanbanDoneRoute
  '/api/equipment/$id': typeof ApiEquipmentIdRouteWithChildren
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/kanban/events': typeof ApiKanbanEventsRoute
  '/api/onshape/parts': typeof ApiOnshapePartsRoute
  '/api/onshape/thumbnail': typeof ApiOnshapeThumbnailRoute
  '/api/onshape/token': typeof ApiOnshapeTokenRoute
  '/api/onshape/version': typeof ApiOnshapeVersionRoute
  '/api/processes/$id': typeof ApiProcessesIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/auth/onshape/callback': typeof AuthOnshapeCallbackRoute
  '/kanban/': typeof MainKanbanIndexRoute
  '/api/equipment/': typeof ApiEquipmentIndexRoute
  '/api/processes/': typeof ApiProcessesIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/auth/onshape/': typeof AuthOnshapeIndexRoute
  '/api/equipment/$id/image': typeof ApiEquipmentIdImageRoute
  '/api/kanban/cards/$id': typeof ApiKanbanCardsIdRouteWithChildren
  '/api/kanban/config/columns': typeof ApiKanbanConfigColumnsRoute
  '/api/mfg/parts/actions': typeof ApiMfgPartsActionsRoute
  '/api/kanban/cards/': typeof ApiKanbanCardsIndexRoute
  '/api/kanban/config/': typeof ApiKanbanConfigIndexRoute
  '/api/kanban/cards/$id/assign': typeof ApiKanbanCardsIdAssignRoute
}
export interface FileRoutesByTo {
  '/onshape_connector': typeof Onshape_connectorRoute
  '/signin': typeof SigninRoute
  '/equipment': typeof MainEquipmentRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/status': typeof AuthStatusRoute
  '/': typeof MainIndexRoute
  '/kanban/done': typeof MainKanbanDoneRoute
  '/api/equipment/$id': typeof ApiEquipmentIdRouteWithChildren
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/kanban/events': typeof ApiKanbanEventsRoute
  '/api/onshape/parts': typeof ApiOnshapePartsRoute
  '/api/onshape/thumbnail': typeof ApiOnshapeThumbnailRoute
  '/api/onshape/token': typeof ApiOnshapeTokenRoute
  '/api/onshape/version': typeof ApiOnshapeVersionRoute
  '/api/processes/$id': typeof ApiProcessesIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/auth/onshape/callback': typeof AuthOnshapeCallbackRoute
  '/kanban': typeof MainKanbanIndexRoute
  '/api/equipment': typeof ApiEquipmentIndexRoute
  '/api/processes': typeof ApiProcessesIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/auth/onshape': typeof AuthOnshapeIndexRoute
  '/api/equipment/$id/image': typeof ApiEquipmentIdImageRoute
  '/api/kanban/cards/$id': typeof ApiKanbanCardsIdRouteWithChildren
  '/api/kanban/config/columns': typeof ApiKanbanConfigColumnsRoute
  '/api/mfg/parts/actions': typeof ApiMfgPartsActionsRoute
  '/api/kanban/cards': typeof ApiKanbanCardsIndexRoute
  '/api/kanban/config': typeof ApiKanbanConfigIndexRoute
  '/api/kanban/cards/$id/assign': typeof ApiKanbanCardsIdAssignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/onshape_connector': typeof Onshape_connectorRoute
  '/signin': typeof SigninRoute
  '/_main/equipment': typeof MainEquipmentRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/status': typeof AuthStatusRoute
  '/_main/': typeof MainIndexRoute
  '/_main/kanban/done': typeof MainKanbanDoneRoute
  '/api/equipment/$id': typeof ApiEquipmentIdRouteWithChildren
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/kanban/events': typeof ApiKanbanEventsRoute
  '/api/onshape/parts': typeof ApiOnshapePartsRoute
  '/api/onshape/thumbnail': typeof ApiOnshapeThumbnailRoute
  '/api/onshape/token': typeof ApiOnshapeTokenRoute
  '/api/onshape/version': typeof ApiOnshapeVersionRoute
  '/api/processes/$id': typeof ApiProcessesIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/auth/onshape/callback': typeof AuthOnshapeCallbackRoute
  '/_main/kanban/': typeof MainKanbanIndexRoute
  '/api/equipment/': typeof ApiEquipmentIndexRoute
  '/api/processes/': typeof ApiProcessesIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/auth/onshape/': typeof AuthOnshapeIndexRoute
  '/api/equipment/$id/image': typeof ApiEquipmentIdImageRoute
  '/api/kanban/cards/$id': typeof ApiKanbanCardsIdRouteWithChildren
  '/api/kanban/config/columns': typeof ApiKanbanConfigColumnsRoute
  '/api/mfg/parts/actions': typeof ApiMfgPartsActionsRoute
  '/api/kanban/cards/': typeof ApiKanbanCardsIndexRoute
  '/api/kanban/config/': typeof ApiKanbanConfigIndexRoute
  '/api/kanban/cards/$id/assign': typeof ApiKanbanCardsIdAssignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onshape_connector'
    | '/signin'
    | '/equipment'
    | '/api/health'
    | '/auth/logout'
    | '/auth/status'
    | '/kanban/done'
    | '/api/equipment/$id'
    | '/api/files/$'
    | '/api/kanban/events'
    | '/api/onshape/parts'
    | '/api/onshape/thumbnail'
    | '/api/onshape/token'
    | '/api/onshape/version'
    | '/api/processes/$id'
    | '/api/users/$id'
    | '/auth/onshape/callback'
    | '/kanban/'
    | '/api/equipment/'
    | '/api/processes/'
    | '/api/users/'
    | '/auth/onshape/'
    | '/api/equipment/$id/image'
    | '/api/kanban/cards/$id'
    | '/api/kanban/config/columns'
    | '/api/mfg/parts/actions'
    | '/api/kanban/cards/'
    | '/api/kanban/config/'
    | '/api/kanban/cards/$id/assign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onshape_connector'
    | '/signin'
    | '/equipment'
    | '/api/health'
    | '/auth/logout'
    | '/auth/status'
    | '/'
    | '/kanban/done'
    | '/api/equipment/$id'
    | '/api/files/$'
    | '/api/kanban/events'
    | '/api/onshape/parts'
    | '/api/onshape/thumbnail'
    | '/api/onshape/token'
    | '/api/onshape/version'
    | '/api/processes/$id'
    | '/api/users/$id'
    | '/auth/onshape/callback'
    | '/kanban'
    | '/api/equipment'
    | '/api/processes'
    | '/api/users'
    | '/auth/onshape'
    | '/api/equipment/$id/image'
    | '/api/kanban/cards/$id'
    | '/api/kanban/config/columns'
    | '/api/mfg/parts/actions'
    | '/api/kanban/cards'
    | '/api/kanban/config'
    | '/api/kanban/cards/$id/assign'
  id:
    | '__root__'
    | '/_main'
    | '/onshape_connector'
    | '/signin'
    | '/_main/equipment'
    | '/api/health'
    | '/auth/logout'
    | '/auth/status'
    | '/_main/'
    | '/_main/kanban/done'
    | '/api/equipment/$id'
    | '/api/files/$'
    | '/api/kanban/events'
    | '/api/onshape/parts'
    | '/api/onshape/thumbnail'
    | '/api/onshape/token'
    | '/api/onshape/version'
    | '/api/processes/$id'
    | '/api/users/$id'
    | '/auth/onshape/callback'
    | '/_main/kanban/'
    | '/api/equipment/'
    | '/api/processes/'
    | '/api/users/'
    | '/auth/onshape/'
    | '/api/equipment/$id/image'
    | '/api/kanban/cards/$id'
    | '/api/kanban/config/columns'
    | '/api/mfg/parts/actions'
    | '/api/kanban/cards/'
    | '/api/kanban/config/'
    | '/api/kanban/cards/$id/assign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  Onshape_connectorRoute: typeof Onshape_connectorRoute
  SigninRoute: typeof SigninRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthStatusRoute: typeof AuthStatusRoute
  ApiEquipmentIdRoute: typeof ApiEquipmentIdRouteWithChildren
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiKanbanEventsRoute: typeof ApiKanbanEventsRoute
  ApiOnshapePartsRoute: typeof ApiOnshapePartsRoute
  ApiOnshapeThumbnailRoute: typeof ApiOnshapeThumbnailRoute
  ApiOnshapeTokenRoute: typeof ApiOnshapeTokenRoute
  ApiOnshapeVersionRoute: typeof ApiOnshapeVersionRoute
  ApiProcessesIdRoute: typeof ApiProcessesIdRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  AuthOnshapeCallbackRoute: typeof AuthOnshapeCallbackRoute
  ApiEquipmentIndexRoute: typeof ApiEquipmentIndexRoute
  ApiProcessesIndexRoute: typeof ApiProcessesIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  AuthOnshapeIndexRoute: typeof AuthOnshapeIndexRoute
  ApiKanbanCardsIdRoute: typeof ApiKanbanCardsIdRouteWithChildren
  ApiKanbanConfigColumnsRoute: typeof ApiKanbanConfigColumnsRoute
  ApiMfgPartsActionsRoute: typeof ApiMfgPartsActionsRoute
  ApiKanbanCardsIndexRoute: typeof ApiKanbanCardsIndexRoute
  ApiKanbanConfigIndexRoute: typeof ApiKanbanConfigIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onshape_connector': {
      id: '/onshape_connector'
      path: '/onshape_connector'
      fullPath: '/onshape_connector'
      preLoaderRoute: typeof Onshape_connectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/equipment': {
      id: '/_main/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof MainEquipmentRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/status': {
      id: '/auth/status'
      path: '/auth/status'
      fullPath: '/auth/status'
      preLoaderRoute: typeof AuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/kanban/': {
      id: '/_main/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof MainKanbanIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/kanban/done': {
      id: '/_main/kanban/done'
      path: '/kanban/done'
      fullPath: '/kanban/done'
      preLoaderRoute: typeof MainKanbanDoneRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/equipment/': {
      id: '/api/equipment/'
      path: '/api/equipment'
      fullPath: '/api/equipment/'
      preLoaderRoute: typeof ApiEquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/equipment/$id': {
      id: '/api/equipment/$id'
      path: '/api/equipment/$id'
      fullPath: '/api/equipment/$id'
      preLoaderRoute: typeof ApiEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/events': {
      id: '/api/kanban/events'
      path: '/api/kanban/events'
      fullPath: '/api/kanban/events'
      preLoaderRoute: typeof ApiKanbanEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onshape/parts': {
      id: '/api/onshape/parts'
      path: '/api/onshape/parts'
      fullPath: '/api/onshape/parts'
      preLoaderRoute: typeof ApiOnshapePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onshape/thumbnail': {
      id: '/api/onshape/thumbnail'
      path: '/api/onshape/thumbnail'
      fullPath: '/api/onshape/thumbnail'
      preLoaderRoute: typeof ApiOnshapeThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onshape/token': {
      id: '/api/onshape/token'
      path: '/api/onshape/token'
      fullPath: '/api/onshape/token'
      preLoaderRoute: typeof ApiOnshapeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onshape/version': {
      id: '/api/onshape/version'
      path: '/api/onshape/version'
      fullPath: '/api/onshape/version'
      preLoaderRoute: typeof ApiOnshapeVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processes/': {
      id: '/api/processes/'
      path: '/api/processes'
      fullPath: '/api/processes/'
      preLoaderRoute: typeof ApiProcessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processes/$id': {
      id: '/api/processes/$id'
      path: '/api/processes/$id'
      fullPath: '/api/processes/$id'
      preLoaderRoute: typeof ApiProcessesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onshape/': {
      id: '/auth/onshape/'
      path: '/auth/onshape'
      fullPath: '/auth/onshape/'
      preLoaderRoute: typeof AuthOnshapeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onshape/callback': {
      id: '/auth/onshape/callback'
      path: '/auth/onshape/callback'
      fullPath: '/auth/onshape/callback'
      preLoaderRoute: typeof AuthOnshapeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/equipment/$id/image': {
      id: '/api/equipment/$id/image'
      path: '/image'
      fullPath: '/api/equipment/$id/image'
      preLoaderRoute: typeof ApiEquipmentIdImageRouteImport
      parentRoute: typeof ApiEquipmentIdRoute
    }
    '/api/kanban/cards/': {
      id: '/api/kanban/cards/'
      path: '/api/kanban/cards'
      fullPath: '/api/kanban/cards/'
      preLoaderRoute: typeof ApiKanbanCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/cards/$id': {
      id: '/api/kanban/cards/$id'
      path: '/api/kanban/cards/$id'
      fullPath: '/api/kanban/cards/$id'
      preLoaderRoute: typeof ApiKanbanCardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/config/': {
      id: '/api/kanban/config/'
      path: '/api/kanban/config'
      fullPath: '/api/kanban/config/'
      preLoaderRoute: typeof ApiKanbanConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/config/columns': {
      id: '/api/kanban/config/columns'
      path: '/api/kanban/config/columns'
      fullPath: '/api/kanban/config/columns'
      preLoaderRoute: typeof ApiKanbanConfigColumnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mfg/parts/actions': {
      id: '/api/mfg/parts/actions'
      path: '/api/mfg/parts/actions'
      fullPath: '/api/mfg/parts/actions'
      preLoaderRoute: typeof ApiMfgPartsActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/cards/$id/assign': {
      id: '/api/kanban/cards/$id/assign'
      path: '/assign'
      fullPath: '/api/kanban/cards/$id/assign'
      preLoaderRoute: typeof ApiKanbanCardsIdAssignRouteImport
      parentRoute: typeof ApiKanbanCardsIdRoute
    }
  }
}

interface MainRouteChildren {
  MainEquipmentRoute: typeof MainEquipmentRoute
  MainIndexRoute: typeof MainIndexRoute
  MainKanbanDoneRoute: typeof MainKanbanDoneRoute
  MainKanbanIndexRoute: typeof MainKanbanIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainEquipmentRoute: MainEquipmentRoute,
  MainIndexRoute: MainIndexRoute,
  MainKanbanDoneRoute: MainKanbanDoneRoute,
  MainKanbanIndexRoute: MainKanbanIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface ApiEquipmentIdRouteChildren {
  ApiEquipmentIdImageRoute: typeof ApiEquipmentIdImageRoute
}

const ApiEquipmentIdRouteChildren: ApiEquipmentIdRouteChildren = {
  ApiEquipmentIdImageRoute: ApiEquipmentIdImageRoute,
}

const ApiEquipmentIdRouteWithChildren = ApiEquipmentIdRoute._addFileChildren(
  ApiEquipmentIdRouteChildren,
)

interface ApiKanbanCardsIdRouteChildren {
  ApiKanbanCardsIdAssignRoute: typeof ApiKanbanCardsIdAssignRoute
}

const ApiKanbanCardsIdRouteChildren: ApiKanbanCardsIdRouteChildren = {
  ApiKanbanCardsIdAssignRoute: ApiKanbanCardsIdAssignRoute,
}

const ApiKanbanCardsIdRouteWithChildren =
  ApiKanbanCardsIdRoute._addFileChildren(ApiKanbanCardsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  Onshape_connectorRoute: Onshape_connectorRoute,
  SigninRoute: SigninRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthStatusRoute: AuthStatusRoute,
  ApiEquipmentIdRoute: ApiEquipmentIdRouteWithChildren,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiKanbanEventsRoute: ApiKanbanEventsRoute,
  ApiOnshapePartsRoute: ApiOnshapePartsRoute,
  ApiOnshapeThumbnailRoute: ApiOnshapeThumbnailRoute,
  ApiOnshapeTokenRoute: ApiOnshapeTokenRoute,
  ApiOnshapeVersionRoute: ApiOnshapeVersionRoute,
  ApiProcessesIdRoute: ApiProcessesIdRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  AuthOnshapeCallbackRoute: AuthOnshapeCallbackRoute,
  ApiEquipmentIndexRoute: ApiEquipmentIndexRoute,
  ApiProcessesIndexRoute: ApiProcessesIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  AuthOnshapeIndexRoute: AuthOnshapeIndexRoute,
  ApiKanbanCardsIdRoute: ApiKanbanCardsIdRouteWithChildren,
  ApiKanbanConfigColumnsRoute: ApiKanbanConfigColumnsRoute,
  ApiMfgPartsActionsRoute: ApiMfgPartsActionsRoute,
  ApiKanbanCardsIndexRoute: ApiKanbanCardsIndexRoute,
  ApiKanbanConfigIndexRoute: ApiKanbanConfigIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
